/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecadastroRouteImport } from './routes/recadastro'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as InscreverRouteImport } from './routes/inscrever'
import { Route as CadastroUsuarioRouteImport } from './routes/cadastro-usuario'
import { Route as CadastroAgitadorRouteImport } from './routes/cadastro-agitador'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtualizacaoRouteImport } from './routes/atualizacao'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermosSlugRouteImport } from './routes/termos.$slug'
import { Route as OptOutTokenRouteImport } from './routes/opt-out.$token'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as EventoSlugRouteImport } from './routes/evento.$slug'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTerritorioRouteImport } from './routes/_authenticated/territorio'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedSegmentosRouteImport } from './routes/_authenticated/segmentos'
import { Route as AuthenticatedRelacionamentoRouteImport } from './routes/_authenticated/relacionamento'
import { Route as AuthenticatedMinhasMissoesRouteImport } from './routes/_authenticated/minhas-missoes'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedDuplicidadesRouteImport } from './routes/_authenticated/duplicidades'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContatosBiRouteImport } from './routes/_authenticated/contatos-bi'
import { Route as AuthenticatedComunicacaoRouteImport } from './routes/_authenticated/comunicacao'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAgitacaoNotificacoesRouteImport } from './routes/_authenticated/agitacao-notificacoes'
import { Route as AuthenticatedAgitacaoRouteImport } from './routes/_authenticated/agitacao'
import { Route as AuthenticatedMissoesAgitacaoIndexRouteImport } from './routes/_authenticated/missoes-agitacao.index'
import { Route as AuthenticatedEntradaDadosIndexRouteImport } from './routes/_authenticated/entrada-dados.index'
import { Route as AuthenticatedContatosIndexRouteImport } from './routes/_authenticated/contatos.index'
import { Route as AuthenticatedComunicacaoIndexRouteImport } from './routes/_authenticated/comunicacao.index'
import { Route as AuthenticatedCampanhasIndexRouteImport } from './routes/_authenticated/campanhas.index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedUsuariosPapeisRouteImport } from './routes/_authenticated/usuarios.papeis'
import { Route as AuthenticatedTriagemSegmentIdRouteImport } from './routes/_authenticated/triagem.$segmentId'
import { Route as AuthenticatedTriagemTarefaTokenRouteImport } from './routes/_authenticated/triagem-tarefa.$token'
import { Route as AuthenticatedMissoesAgitacaoMissionIdRouteImport } from './routes/_authenticated/missoes-agitacao.$missionId'
import { Route as AuthenticatedEntradaDadosIdRouteImport } from './routes/_authenticated/entrada-dados.$id'
import { Route as AuthenticatedContatosIdRouteImport } from './routes/_authenticated/contatos.$id'
import { Route as AuthenticatedComunicacaoInboxRouteImport } from './routes/_authenticated/comunicacao.inbox'
import { Route as AuthenticatedComunicacaoContatosRouteImport } from './routes/_authenticated/comunicacao.contatos'
import { Route as AuthenticatedCampanhasIdRouteImport } from './routes/_authenticated/campanhas.$id'
import { Route as MissaoMissionIdContatoContactIdRouteImport } from './routes/missao/$missionId/contato/$contactId'
import { Route as ApiPublicZapiEventoRouteImport } from './routes/api/public/zapi/$evento'
import { Route as ApiPublicPushVapidRouteImport } from './routes/api/public/push/vapid'
import { Route as ApiPublicPushUnsubscribeRouteImport } from './routes/api/public/push/unsubscribe'
import { Route as ApiPublicPushSubscribeRouteImport } from './routes/api/public/push/subscribe'
import { Route as ApiPublicLegalPagesSlugRouteImport } from './routes/api/public/legal-pages/$slug'
import { Route as ApiPublicJobsProcessCampaignQueueRouteImport } from './routes/api/public/jobs/process-campaign-queue'
import { Route as ApiPublicFormsRecadastroRouteImport } from './routes/api/public/forms/recadastro'
import { Route as ApiPublicFormsOptOutRouteImport } from './routes/api/public/forms/opt-out'
import { Route as ApiPublicFormsInscreverRouteImport } from './routes/api/public/forms/inscrever'
import { Route as ApiPublicFormsCadastroUsuarioRouteImport } from './routes/api/public/forms/cadastro-usuario'
import { Route as ApiPublicFormsCadastroAgitadorRouteImport } from './routes/api/public/forms/cadastro-agitador'
import { Route as ApiPublicFormsSlugRouteImport } from './routes/api/public/forms/$slug'
import { Route as ApiPublicEventsSlugRouteImport } from './routes/api/public/events/$slug'
import { Route as ApiPublicCepCepRouteImport } from './routes/api/public/cep.$cep'
import { Route as ApiPublicFormsSlugSectionProgressRouteImport } from './routes/api/public/forms/$slug/section-progress'
import { Route as ApiPublicFormsSlugAccountSectionRouteImport } from './routes/api/public/forms/$slug/account-section'
import { Route as ApiPublicEventsSlugRsvpRouteImport } from './routes/api/public/events/$slug/rsvp'
import { Route as ApiPublicEventsSlugOgImageRouteImport } from './routes/api/public/events/$slug/og-image'
import { Route as ApiPublicEventsSlugIcsRouteImport } from './routes/api/public/events/$slug/ics'
import { Route as ApiPublicEventsSlugCoverRouteImport } from './routes/api/public/events/$slug/cover'
import { Route as ApiPublicAgitationMissionsMissionIdOgImageRouteImport } from './routes/api/public/agitation-missions/$missionId/og-image'
import { Route as ApiPublicAgitationMissionsMissionIdMediaRouteImport } from './routes/api/public/agitation-missions/$missionId/media'
import { Route as ApiPublicAgitationMissionsMissionIdContactIdRouteImport } from './routes/api/public/agitation-missions/$missionId/$contactId'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecadastroRoute = RecadastroRouteImport.update({
  id: '/recadastro',
  path: '/recadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const InscreverRoute = InscreverRouteImport.update({
  id: '/inscrever',
  path: '/inscrever',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroUsuarioRoute = CadastroUsuarioRouteImport.update({
  id: '/cadastro-usuario',
  path: '/cadastro-usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAgitadorRoute = CadastroAgitadorRouteImport.update({
  id: '/cadastro-agitador',
  path: '/cadastro-agitador',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizacaoRoute = AtualizacaoRouteImport.update({
  id: '/atualizacao',
  path: '/atualizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosSlugRoute = TermosSlugRouteImport.update({
  id: '/termos/$slug',
  path: '/termos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OptOutTokenRoute = OptOutTokenRouteImport.update({
  id: '/opt-out/$token',
  path: '/opt-out/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoSlugRoute = EventoSlugRouteImport.update({
  id: '/evento/$slug',
  path: '/evento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTerritorioRoute = AuthenticatedTerritorioRouteImport.update({
  id: '/territorio',
  path: '/territorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegmentosRoute = AuthenticatedSegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelacionamentoRoute =
  AuthenticatedRelacionamentoRouteImport.update({
    id: '/relacionamento',
    path: '/relacionamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasMissoesRoute =
  AuthenticatedMinhasMissoesRouteImport.update({
    id: '/minhas-missoes',
    path: '/minhas-missoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuplicidadesRoute =
  AuthenticatedDuplicidadesRouteImport.update({
    id: '/duplicidades',
    path: '/duplicidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosBiRoute = AuthenticatedContatosBiRouteImport.update({
  id: '/contatos-bi',
  path: '/contatos-bi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunicacaoRoute =
  AuthenticatedComunicacaoRouteImport.update({
    id: '/comunicacao',
    path: '/comunicacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgitacaoNotificacoesRoute =
  AuthenticatedAgitacaoNotificacoesRouteImport.update({
    id: '/agitacao-notificacoes',
    path: '/agitacao-notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgitacaoRoute = AuthenticatedAgitacaoRouteImport.update({
  id: '/agitacao',
  path: '/agitacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissoesAgitacaoIndexRoute =
  AuthenticatedMissoesAgitacaoIndexRouteImport.update({
    id: '/missoes-agitacao/',
    path: '/missoes-agitacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntradaDadosIndexRoute =
  AuthenticatedEntradaDadosIndexRouteImport.update({
    id: '/entrada-dados/',
    path: '/entrada-dados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContatosIndexRoute =
  AuthenticatedContatosIndexRouteImport.update({
    id: '/contatos/',
    path: '/contatos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicacaoIndexRoute =
  AuthenticatedComunicacaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComunicacaoRoute,
  } as any)
const AuthenticatedCampanhasIndexRoute =
  AuthenticatedCampanhasIndexRouteImport.update({
    id: '/campanhas/',
    path: '/campanhas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosPapeisRoute =
  AuthenticatedUsuariosPapeisRouteImport.update({
    id: '/papeis',
    path: '/papeis',
    getParentRoute: () => AuthenticatedUsuariosRoute,
  } as any)
const AuthenticatedTriagemSegmentIdRoute =
  AuthenticatedTriagemSegmentIdRouteImport.update({
    id: '/triagem/$segmentId',
    path: '/triagem/$segmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTriagemTarefaTokenRoute =
  AuthenticatedTriagemTarefaTokenRouteImport.update({
    id: '/triagem-tarefa/$token',
    path: '/triagem-tarefa/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissoesAgitacaoMissionIdRoute =
  AuthenticatedMissoesAgitacaoMissionIdRouteImport.update({
    id: '/missoes-agitacao/$missionId',
    path: '/missoes-agitacao/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntradaDadosIdRoute =
  AuthenticatedEntradaDadosIdRouteImport.update({
    id: '/entrada-dados/$id',
    path: '/entrada-dados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContatosIdRoute = AuthenticatedContatosIdRouteImport.update({
  id: '/contatos/$id',
  path: '/contatos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunicacaoInboxRoute =
  AuthenticatedComunicacaoInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedComunicacaoRoute,
  } as any)
const AuthenticatedComunicacaoContatosRoute =
  AuthenticatedComunicacaoContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedComunicacaoRoute,
  } as any)
const AuthenticatedCampanhasIdRoute =
  AuthenticatedCampanhasIdRouteImport.update({
    id: '/campanhas/$id',
    path: '/campanhas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MissaoMissionIdContatoContactIdRoute =
  MissaoMissionIdContatoContactIdRouteImport.update({
    id: '/missao/$missionId/contato/$contactId',
    path: '/missao/$missionId/contato/$contactId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicZapiEventoRoute = ApiPublicZapiEventoRouteImport.update({
  id: '/api/public/zapi/$evento',
  path: '/api/public/zapi/$evento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushVapidRoute = ApiPublicPushVapidRouteImport.update({
  id: '/api/public/push/vapid',
  path: '/api/public/push/vapid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushUnsubscribeRoute =
  ApiPublicPushUnsubscribeRouteImport.update({
    id: '/api/public/push/unsubscribe',
    path: '/api/public/push/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushSubscribeRoute = ApiPublicPushSubscribeRouteImport.update({
  id: '/api/public/push/subscribe',
  path: '/api/public/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLegalPagesSlugRoute = ApiPublicLegalPagesSlugRouteImport.update({
  id: '/api/public/legal-pages/$slug',
  path: '/api/public/legal-pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsProcessCampaignQueueRoute =
  ApiPublicJobsProcessCampaignQueueRouteImport.update({
    id: '/api/public/jobs/process-campaign-queue',
    path: '/api/public/jobs/process-campaign-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormsRecadastroRoute =
  ApiPublicFormsRecadastroRouteImport.update({
    id: '/api/public/forms/recadastro',
    path: '/api/public/forms/recadastro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormsOptOutRoute = ApiPublicFormsOptOutRouteImport.update({
  id: '/api/public/forms/opt-out',
  path: '/api/public/forms/opt-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsInscreverRoute = ApiPublicFormsInscreverRouteImport.update({
  id: '/api/public/forms/inscrever',
  path: '/api/public/forms/inscrever',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsCadastroUsuarioRoute =
  ApiPublicFormsCadastroUsuarioRouteImport.update({
    id: '/api/public/forms/cadastro-usuario',
    path: '/api/public/forms/cadastro-usuario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormsCadastroAgitadorRoute =
  ApiPublicFormsCadastroAgitadorRouteImport.update({
    id: '/api/public/forms/cadastro-agitador',
    path: '/api/public/forms/cadastro-agitador',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormsSlugRoute = ApiPublicFormsSlugRouteImport.update({
  id: '/api/public/forms/$slug',
  path: '/api/public/forms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsSlugRoute = ApiPublicEventsSlugRouteImport.update({
  id: '/api/public/events/$slug',
  path: '/api/public/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCepCepRoute = ApiPublicCepCepRouteImport.update({
  id: '/api/public/cep/$cep',
  path: '/api/public/cep/$cep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugSectionProgressRoute =
  ApiPublicFormsSlugSectionProgressRouteImport.update({
    id: '/section-progress',
    path: '/section-progress',
    getParentRoute: () => ApiPublicFormsSlugRoute,
  } as any)
const ApiPublicFormsSlugAccountSectionRoute =
  ApiPublicFormsSlugAccountSectionRouteImport.update({
    id: '/account-section',
    path: '/account-section',
    getParentRoute: () => ApiPublicFormsSlugRoute,
  } as any)
const ApiPublicEventsSlugRsvpRoute = ApiPublicEventsSlugRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => ApiPublicEventsSlugRoute,
} as any)
const ApiPublicEventsSlugOgImageRoute =
  ApiPublicEventsSlugOgImageRouteImport.update({
    id: '/og-image',
    path: '/og-image',
    getParentRoute: () => ApiPublicEventsSlugRoute,
  } as any)
const ApiPublicEventsSlugIcsRoute = ApiPublicEventsSlugIcsRouteImport.update({
  id: '/ics',
  path: '/ics',
  getParentRoute: () => ApiPublicEventsSlugRoute,
} as any)
const ApiPublicEventsSlugCoverRoute =
  ApiPublicEventsSlugCoverRouteImport.update({
    id: '/cover',
    path: '/cover',
    getParentRoute: () => ApiPublicEventsSlugRoute,
  } as any)
const ApiPublicAgitationMissionsMissionIdOgImageRoute =
  ApiPublicAgitationMissionsMissionIdOgImageRouteImport.update({
    id: '/api/public/agitation-missions/$missionId/og-image',
    path: '/api/public/agitation-missions/$missionId/og-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgitationMissionsMissionIdMediaRoute =
  ApiPublicAgitationMissionsMissionIdMediaRouteImport.update({
    id: '/api/public/agitation-missions/$missionId/media',
    path: '/api/public/agitation-missions/$missionId/media',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgitationMissionsMissionIdContactIdRoute =
  ApiPublicAgitationMissionsMissionIdContactIdRouteImport.update({
    id: '/api/public/agitation-missions/$missionId/$contactId',
    path: '/api/public/agitation-missions/$missionId/$contactId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/atualizacao': typeof AtualizacaoRoute
  '/auth': typeof AuthRoute
  '/cadastro-agitador': typeof CadastroAgitadorRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/inscrever': typeof InscreverRoute
  '/obrigado': typeof ObrigadoRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recadastro': typeof RecadastroRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agitacao': typeof AuthenticatedAgitacaoRoute
  '/agitacao-notificacoes': typeof AuthenticatedAgitacaoNotificacoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/comunicacao': typeof AuthenticatedComunicacaoRouteWithChildren
  '/contatos-bi': typeof AuthenticatedContatosBiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duplicidades': typeof AuthenticatedDuplicidadesRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/links': typeof AuthenticatedLinksRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/minhas-missoes': typeof AuthenticatedMinhasMissoesRoute
  '/relacionamento': typeof AuthenticatedRelacionamentoRoute
  '/segmentos': typeof AuthenticatedSegmentosRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/territorio': typeof AuthenticatedTerritorioRoute
  '/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/opt-out/$token': typeof OptOutTokenRoute
  '/termos/$slug': typeof TermosSlugRoute
  '/campanhas/$id': typeof AuthenticatedCampanhasIdRoute
  '/comunicacao/contatos': typeof AuthenticatedComunicacaoContatosRoute
  '/comunicacao/inbox': typeof AuthenticatedComunicacaoInboxRoute
  '/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/entrada-dados/$id': typeof AuthenticatedEntradaDadosIdRoute
  '/missoes-agitacao/$missionId': typeof AuthenticatedMissoesAgitacaoMissionIdRoute
  '/triagem-tarefa/$token': typeof AuthenticatedTriagemTarefaTokenRoute
  '/triagem/$segmentId': typeof AuthenticatedTriagemSegmentIdRoute
  '/usuarios/papeis': typeof AuthenticatedUsuariosPapeisRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/campanhas/': typeof AuthenticatedCampanhasIndexRoute
  '/comunicacao/': typeof AuthenticatedComunicacaoIndexRoute
  '/contatos/': typeof AuthenticatedContatosIndexRoute
  '/entrada-dados/': typeof AuthenticatedEntradaDadosIndexRoute
  '/missoes-agitacao/': typeof AuthenticatedMissoesAgitacaoIndexRoute
  '/api/public/cep/$cep': typeof ApiPublicCepCepRoute
  '/api/public/events/$slug': typeof ApiPublicEventsSlugRouteWithChildren
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRouteWithChildren
  '/api/public/forms/cadastro-agitador': typeof ApiPublicFormsCadastroAgitadorRoute
  '/api/public/forms/cadastro-usuario': typeof ApiPublicFormsCadastroUsuarioRoute
  '/api/public/forms/inscrever': typeof ApiPublicFormsInscreverRoute
  '/api/public/forms/opt-out': typeof ApiPublicFormsOptOutRoute
  '/api/public/forms/recadastro': typeof ApiPublicFormsRecadastroRoute
  '/api/public/jobs/process-campaign-queue': typeof ApiPublicJobsProcessCampaignQueueRoute
  '/api/public/legal-pages/$slug': typeof ApiPublicLegalPagesSlugRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/push/vapid': typeof ApiPublicPushVapidRoute
  '/api/public/zapi/$evento': typeof ApiPublicZapiEventoRoute
  '/missao/$missionId/contato/$contactId': typeof MissaoMissionIdContatoContactIdRoute
  '/api/public/agitation-missions/$missionId/$contactId': typeof ApiPublicAgitationMissionsMissionIdContactIdRoute
  '/api/public/agitation-missions/$missionId/media': typeof ApiPublicAgitationMissionsMissionIdMediaRoute
  '/api/public/agitation-missions/$missionId/og-image': typeof ApiPublicAgitationMissionsMissionIdOgImageRoute
  '/api/public/events/$slug/cover': typeof ApiPublicEventsSlugCoverRoute
  '/api/public/events/$slug/ics': typeof ApiPublicEventsSlugIcsRoute
  '/api/public/events/$slug/og-image': typeof ApiPublicEventsSlugOgImageRoute
  '/api/public/events/$slug/rsvp': typeof ApiPublicEventsSlugRsvpRoute
  '/api/public/forms/$slug/account-section': typeof ApiPublicFormsSlugAccountSectionRoute
  '/api/public/forms/$slug/section-progress': typeof ApiPublicFormsSlugSectionProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/atualizacao': typeof AtualizacaoRoute
  '/auth': typeof AuthRoute
  '/cadastro-agitador': typeof CadastroAgitadorRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/inscrever': typeof InscreverRoute
  '/obrigado': typeof ObrigadoRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recadastro': typeof RecadastroRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agitacao': typeof AuthenticatedAgitacaoRoute
  '/agitacao-notificacoes': typeof AuthenticatedAgitacaoNotificacoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/contatos-bi': typeof AuthenticatedContatosBiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duplicidades': typeof AuthenticatedDuplicidadesRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/links': typeof AuthenticatedLinksRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/minhas-missoes': typeof AuthenticatedMinhasMissoesRoute
  '/relacionamento': typeof AuthenticatedRelacionamentoRoute
  '/segmentos': typeof AuthenticatedSegmentosRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/territorio': typeof AuthenticatedTerritorioRoute
  '/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/opt-out/$token': typeof OptOutTokenRoute
  '/termos/$slug': typeof TermosSlugRoute
  '/campanhas/$id': typeof AuthenticatedCampanhasIdRoute
  '/comunicacao/contatos': typeof AuthenticatedComunicacaoContatosRoute
  '/comunicacao/inbox': typeof AuthenticatedComunicacaoInboxRoute
  '/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/entrada-dados/$id': typeof AuthenticatedEntradaDadosIdRoute
  '/missoes-agitacao/$missionId': typeof AuthenticatedMissoesAgitacaoMissionIdRoute
  '/triagem-tarefa/$token': typeof AuthenticatedTriagemTarefaTokenRoute
  '/triagem/$segmentId': typeof AuthenticatedTriagemSegmentIdRoute
  '/usuarios/papeis': typeof AuthenticatedUsuariosPapeisRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/campanhas': typeof AuthenticatedCampanhasIndexRoute
  '/comunicacao': typeof AuthenticatedComunicacaoIndexRoute
  '/contatos': typeof AuthenticatedContatosIndexRoute
  '/entrada-dados': typeof AuthenticatedEntradaDadosIndexRoute
  '/missoes-agitacao': typeof AuthenticatedMissoesAgitacaoIndexRoute
  '/api/public/cep/$cep': typeof ApiPublicCepCepRoute
  '/api/public/events/$slug': typeof ApiPublicEventsSlugRouteWithChildren
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRouteWithChildren
  '/api/public/forms/cadastro-agitador': typeof ApiPublicFormsCadastroAgitadorRoute
  '/api/public/forms/cadastro-usuario': typeof ApiPublicFormsCadastroUsuarioRoute
  '/api/public/forms/inscrever': typeof ApiPublicFormsInscreverRoute
  '/api/public/forms/opt-out': typeof ApiPublicFormsOptOutRoute
  '/api/public/forms/recadastro': typeof ApiPublicFormsRecadastroRoute
  '/api/public/jobs/process-campaign-queue': typeof ApiPublicJobsProcessCampaignQueueRoute
  '/api/public/legal-pages/$slug': typeof ApiPublicLegalPagesSlugRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/push/vapid': typeof ApiPublicPushVapidRoute
  '/api/public/zapi/$evento': typeof ApiPublicZapiEventoRoute
  '/missao/$missionId/contato/$contactId': typeof MissaoMissionIdContatoContactIdRoute
  '/api/public/agitation-missions/$missionId/$contactId': typeof ApiPublicAgitationMissionsMissionIdContactIdRoute
  '/api/public/agitation-missions/$missionId/media': typeof ApiPublicAgitationMissionsMissionIdMediaRoute
  '/api/public/agitation-missions/$missionId/og-image': typeof ApiPublicAgitationMissionsMissionIdOgImageRoute
  '/api/public/events/$slug/cover': typeof ApiPublicEventsSlugCoverRoute
  '/api/public/events/$slug/ics': typeof ApiPublicEventsSlugIcsRoute
  '/api/public/events/$slug/og-image': typeof ApiPublicEventsSlugOgImageRoute
  '/api/public/events/$slug/rsvp': typeof ApiPublicEventsSlugRsvpRoute
  '/api/public/forms/$slug/account-section': typeof ApiPublicFormsSlugAccountSectionRoute
  '/api/public/forms/$slug/section-progress': typeof ApiPublicFormsSlugSectionProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/atualizacao': typeof AtualizacaoRoute
  '/auth': typeof AuthRoute
  '/cadastro-agitador': typeof CadastroAgitadorRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/inscrever': typeof InscreverRoute
  '/obrigado': typeof ObrigadoRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recadastro': typeof RecadastroRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/agitacao': typeof AuthenticatedAgitacaoRoute
  '/_authenticated/agitacao-notificacoes': typeof AuthenticatedAgitacaoNotificacoesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/comunicacao': typeof AuthenticatedComunicacaoRouteWithChildren
  '/_authenticated/contatos-bi': typeof AuthenticatedContatosBiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/duplicidades': typeof AuthenticatedDuplicidadesRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/minhas-missoes': typeof AuthenticatedMinhasMissoesRoute
  '/_authenticated/relacionamento': typeof AuthenticatedRelacionamentoRoute
  '/_authenticated/segmentos': typeof AuthenticatedSegmentosRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/_authenticated/territorio': typeof AuthenticatedTerritorioRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/opt-out/$token': typeof OptOutTokenRoute
  '/termos/$slug': typeof TermosSlugRoute
  '/_authenticated/campanhas/$id': typeof AuthenticatedCampanhasIdRoute
  '/_authenticated/comunicacao/contatos': typeof AuthenticatedComunicacaoContatosRoute
  '/_authenticated/comunicacao/inbox': typeof AuthenticatedComunicacaoInboxRoute
  '/_authenticated/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/_authenticated/entrada-dados/$id': typeof AuthenticatedEntradaDadosIdRoute
  '/_authenticated/missoes-agitacao/$missionId': typeof AuthenticatedMissoesAgitacaoMissionIdRoute
  '/_authenticated/triagem-tarefa/$token': typeof AuthenticatedTriagemTarefaTokenRoute
  '/_authenticated/triagem/$segmentId': typeof AuthenticatedTriagemSegmentIdRoute
  '/_authenticated/usuarios/papeis': typeof AuthenticatedUsuariosPapeisRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/campanhas/': typeof AuthenticatedCampanhasIndexRoute
  '/_authenticated/comunicacao/': typeof AuthenticatedComunicacaoIndexRoute
  '/_authenticated/contatos/': typeof AuthenticatedContatosIndexRoute
  '/_authenticated/entrada-dados/': typeof AuthenticatedEntradaDadosIndexRoute
  '/_authenticated/missoes-agitacao/': typeof AuthenticatedMissoesAgitacaoIndexRoute
  '/api/public/cep/$cep': typeof ApiPublicCepCepRoute
  '/api/public/events/$slug': typeof ApiPublicEventsSlugRouteWithChildren
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRouteWithChildren
  '/api/public/forms/cadastro-agitador': typeof ApiPublicFormsCadastroAgitadorRoute
  '/api/public/forms/cadastro-usuario': typeof ApiPublicFormsCadastroUsuarioRoute
  '/api/public/forms/inscrever': typeof ApiPublicFormsInscreverRoute
  '/api/public/forms/opt-out': typeof ApiPublicFormsOptOutRoute
  '/api/public/forms/recadastro': typeof ApiPublicFormsRecadastroRoute
  '/api/public/jobs/process-campaign-queue': typeof ApiPublicJobsProcessCampaignQueueRoute
  '/api/public/legal-pages/$slug': typeof ApiPublicLegalPagesSlugRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/push/vapid': typeof ApiPublicPushVapidRoute
  '/api/public/zapi/$evento': typeof ApiPublicZapiEventoRoute
  '/missao/$missionId/contato/$contactId': typeof MissaoMissionIdContatoContactIdRoute
  '/api/public/agitation-missions/$missionId/$contactId': typeof ApiPublicAgitationMissionsMissionIdContactIdRoute
  '/api/public/agitation-missions/$missionId/media': typeof ApiPublicAgitationMissionsMissionIdMediaRoute
  '/api/public/agitation-missions/$missionId/og-image': typeof ApiPublicAgitationMissionsMissionIdOgImageRoute
  '/api/public/events/$slug/cover': typeof ApiPublicEventsSlugCoverRoute
  '/api/public/events/$slug/ics': typeof ApiPublicEventsSlugIcsRoute
  '/api/public/events/$slug/og-image': typeof ApiPublicEventsSlugOgImageRoute
  '/api/public/events/$slug/rsvp': typeof ApiPublicEventsSlugRsvpRoute
  '/api/public/forms/$slug/account-section': typeof ApiPublicFormsSlugAccountSectionRoute
  '/api/public/forms/$slug/section-progress': typeof ApiPublicFormsSlugSectionProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/atualizacao'
    | '/auth'
    | '/cadastro-agitador'
    | '/cadastro-usuario'
    | '/inscrever'
    | '/obrigado'
    | '/primeiro-acesso'
    | '/recadastro'
    | '/redefinir-senha'
    | '/agitacao'
    | '/agitacao-notificacoes'
    | '/calendario'
    | '/comunicacao'
    | '/contatos-bi'
    | '/dashboard'
    | '/duplicidades'
    | '/eventos'
    | '/importar'
    | '/inbox'
    | '/links'
    | '/mapa'
    | '/mensagens'
    | '/minhas-missoes'
    | '/relacionamento'
    | '/segmentos'
    | '/tags'
    | '/territorio'
    | '/usuarios'
    | '/whatsapp'
    | '/evento/$slug'
    | '/f/$slug'
    | '/opt-out/$token'
    | '/termos/$slug'
    | '/campanhas/$id'
    | '/comunicacao/contatos'
    | '/comunicacao/inbox'
    | '/contatos/$id'
    | '/entrada-dados/$id'
    | '/missoes-agitacao/$missionId'
    | '/triagem-tarefa/$token'
    | '/triagem/$segmentId'
    | '/usuarios/papeis'
    | '/api/public/bootstrap-admin'
    | '/campanhas/'
    | '/comunicacao/'
    | '/contatos/'
    | '/entrada-dados/'
    | '/missoes-agitacao/'
    | '/api/public/cep/$cep'
    | '/api/public/events/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/forms/cadastro-agitador'
    | '/api/public/forms/cadastro-usuario'
    | '/api/public/forms/inscrever'
    | '/api/public/forms/opt-out'
    | '/api/public/forms/recadastro'
    | '/api/public/jobs/process-campaign-queue'
    | '/api/public/legal-pages/$slug'
    | '/api/public/push/subscribe'
    | '/api/public/push/unsubscribe'
    | '/api/public/push/vapid'
    | '/api/public/zapi/$evento'
    | '/missao/$missionId/contato/$contactId'
    | '/api/public/agitation-missions/$missionId/$contactId'
    | '/api/public/agitation-missions/$missionId/media'
    | '/api/public/agitation-missions/$missionId/og-image'
    | '/api/public/events/$slug/cover'
    | '/api/public/events/$slug/ics'
    | '/api/public/events/$slug/og-image'
    | '/api/public/events/$slug/rsvp'
    | '/api/public/forms/$slug/account-section'
    | '/api/public/forms/$slug/section-progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/atualizacao'
    | '/auth'
    | '/cadastro-agitador'
    | '/cadastro-usuario'
    | '/inscrever'
    | '/obrigado'
    | '/primeiro-acesso'
    | '/recadastro'
    | '/redefinir-senha'
    | '/agitacao'
    | '/agitacao-notificacoes'
    | '/calendario'
    | '/contatos-bi'
    | '/dashboard'
    | '/duplicidades'
    | '/eventos'
    | '/importar'
    | '/inbox'
    | '/links'
    | '/mapa'
    | '/mensagens'
    | '/minhas-missoes'
    | '/relacionamento'
    | '/segmentos'
    | '/tags'
    | '/territorio'
    | '/usuarios'
    | '/whatsapp'
    | '/evento/$slug'
    | '/f/$slug'
    | '/opt-out/$token'
    | '/termos/$slug'
    | '/campanhas/$id'
    | '/comunicacao/contatos'
    | '/comunicacao/inbox'
    | '/contatos/$id'
    | '/entrada-dados/$id'
    | '/missoes-agitacao/$missionId'
    | '/triagem-tarefa/$token'
    | '/triagem/$segmentId'
    | '/usuarios/papeis'
    | '/api/public/bootstrap-admin'
    | '/campanhas'
    | '/comunicacao'
    | '/contatos'
    | '/entrada-dados'
    | '/missoes-agitacao'
    | '/api/public/cep/$cep'
    | '/api/public/events/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/forms/cadastro-agitador'
    | '/api/public/forms/cadastro-usuario'
    | '/api/public/forms/inscrever'
    | '/api/public/forms/opt-out'
    | '/api/public/forms/recadastro'
    | '/api/public/jobs/process-campaign-queue'
    | '/api/public/legal-pages/$slug'
    | '/api/public/push/subscribe'
    | '/api/public/push/unsubscribe'
    | '/api/public/push/vapid'
    | '/api/public/zapi/$evento'
    | '/missao/$missionId/contato/$contactId'
    | '/api/public/agitation-missions/$missionId/$contactId'
    | '/api/public/agitation-missions/$missionId/media'
    | '/api/public/agitation-missions/$missionId/og-image'
    | '/api/public/events/$slug/cover'
    | '/api/public/events/$slug/ics'
    | '/api/public/events/$slug/og-image'
    | '/api/public/events/$slug/rsvp'
    | '/api/public/forms/$slug/account-section'
    | '/api/public/forms/$slug/section-progress'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aceitar-convite'
    | '/atualizacao'
    | '/auth'
    | '/cadastro-agitador'
    | '/cadastro-usuario'
    | '/inscrever'
    | '/obrigado'
    | '/primeiro-acesso'
    | '/recadastro'
    | '/redefinir-senha'
    | '/_authenticated/agitacao'
    | '/_authenticated/agitacao-notificacoes'
    | '/_authenticated/calendario'
    | '/_authenticated/comunicacao'
    | '/_authenticated/contatos-bi'
    | '/_authenticated/dashboard'
    | '/_authenticated/duplicidades'
    | '/_authenticated/eventos'
    | '/_authenticated/importar'
    | '/_authenticated/inbox'
    | '/_authenticated/links'
    | '/_authenticated/mapa'
    | '/_authenticated/mensagens'
    | '/_authenticated/minhas-missoes'
    | '/_authenticated/relacionamento'
    | '/_authenticated/segmentos'
    | '/_authenticated/tags'
    | '/_authenticated/territorio'
    | '/_authenticated/usuarios'
    | '/_authenticated/whatsapp'
    | '/evento/$slug'
    | '/f/$slug'
    | '/opt-out/$token'
    | '/termos/$slug'
    | '/_authenticated/campanhas/$id'
    | '/_authenticated/comunicacao/contatos'
    | '/_authenticated/comunicacao/inbox'
    | '/_authenticated/contatos/$id'
    | '/_authenticated/entrada-dados/$id'
    | '/_authenticated/missoes-agitacao/$missionId'
    | '/_authenticated/triagem-tarefa/$token'
    | '/_authenticated/triagem/$segmentId'
    | '/_authenticated/usuarios/papeis'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/campanhas/'
    | '/_authenticated/comunicacao/'
    | '/_authenticated/contatos/'
    | '/_authenticated/entrada-dados/'
    | '/_authenticated/missoes-agitacao/'
    | '/api/public/cep/$cep'
    | '/api/public/events/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/forms/cadastro-agitador'
    | '/api/public/forms/cadastro-usuario'
    | '/api/public/forms/inscrever'
    | '/api/public/forms/opt-out'
    | '/api/public/forms/recadastro'
    | '/api/public/jobs/process-campaign-queue'
    | '/api/public/legal-pages/$slug'
    | '/api/public/push/subscribe'
    | '/api/public/push/unsubscribe'
    | '/api/public/push/vapid'
    | '/api/public/zapi/$evento'
    | '/missao/$missionId/contato/$contactId'
    | '/api/public/agitation-missions/$missionId/$contactId'
    | '/api/public/agitation-missions/$missionId/media'
    | '/api/public/agitation-missions/$missionId/og-image'
    | '/api/public/events/$slug/cover'
    | '/api/public/events/$slug/ics'
    | '/api/public/events/$slug/og-image'
    | '/api/public/events/$slug/rsvp'
    | '/api/public/forms/$slug/account-section'
    | '/api/public/forms/$slug/section-progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  AtualizacaoRoute: typeof AtualizacaoRoute
  AuthRoute: typeof AuthRoute
  CadastroAgitadorRoute: typeof CadastroAgitadorRoute
  CadastroUsuarioRoute: typeof CadastroUsuarioRoute
  InscreverRoute: typeof InscreverRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  RecadastroRoute: typeof RecadastroRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  EventoSlugRoute: typeof EventoSlugRoute
  FSlugRoute: typeof FSlugRoute
  OptOutTokenRoute: typeof OptOutTokenRoute
  TermosSlugRoute: typeof TermosSlugRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicCepCepRoute: typeof ApiPublicCepCepRoute
  ApiPublicEventsSlugRoute: typeof ApiPublicEventsSlugRouteWithChildren
  ApiPublicFormsSlugRoute: typeof ApiPublicFormsSlugRouteWithChildren
  ApiPublicFormsCadastroAgitadorRoute: typeof ApiPublicFormsCadastroAgitadorRoute
  ApiPublicFormsCadastroUsuarioRoute: typeof ApiPublicFormsCadastroUsuarioRoute
  ApiPublicFormsInscreverRoute: typeof ApiPublicFormsInscreverRoute
  ApiPublicFormsOptOutRoute: typeof ApiPublicFormsOptOutRoute
  ApiPublicFormsRecadastroRoute: typeof ApiPublicFormsRecadastroRoute
  ApiPublicJobsProcessCampaignQueueRoute: typeof ApiPublicJobsProcessCampaignQueueRoute
  ApiPublicLegalPagesSlugRoute: typeof ApiPublicLegalPagesSlugRoute
  ApiPublicPushSubscribeRoute: typeof ApiPublicPushSubscribeRoute
  ApiPublicPushUnsubscribeRoute: typeof ApiPublicPushUnsubscribeRoute
  ApiPublicPushVapidRoute: typeof ApiPublicPushVapidRoute
  ApiPublicZapiEventoRoute: typeof ApiPublicZapiEventoRoute
  MissaoMissionIdContatoContactIdRoute: typeof MissaoMissionIdContatoContactIdRoute
  ApiPublicAgitationMissionsMissionIdContactIdRoute: typeof ApiPublicAgitationMissionsMissionIdContactIdRoute
  ApiPublicAgitationMissionsMissionIdMediaRoute: typeof ApiPublicAgitationMissionsMissionIdMediaRoute
  ApiPublicAgitationMissionsMissionIdOgImageRoute: typeof ApiPublicAgitationMissionsMissionIdOgImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recadastro': {
      id: '/recadastro'
      path: '/recadastro'
      fullPath: '/recadastro'
      preLoaderRoute: typeof RecadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscrever': {
      id: '/inscrever'
      path: '/inscrever'
      fullPath: '/inscrever'
      preLoaderRoute: typeof InscreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-usuario': {
      id: '/cadastro-usuario'
      path: '/cadastro-usuario'
      fullPath: '/cadastro-usuario'
      preLoaderRoute: typeof CadastroUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-agitador': {
      id: '/cadastro-agitador'
      path: '/cadastro-agitador'
      fullPath: '/cadastro-agitador'
      preLoaderRoute: typeof CadastroAgitadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizacao': {
      id: '/atualizacao'
      path: '/atualizacao'
      fullPath: '/atualizacao'
      preLoaderRoute: typeof AtualizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos/$slug': {
      id: '/termos/$slug'
      path: '/termos/$slug'
      fullPath: '/termos/$slug'
      preLoaderRoute: typeof TermosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opt-out/$token': {
      id: '/opt-out/$token'
      path: '/opt-out/$token'
      fullPath: '/opt-out/$token'
      preLoaderRoute: typeof OptOutTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$slug': {
      id: '/evento/$slug'
      path: '/evento/$slug'
      fullPath: '/evento/$slug'
      preLoaderRoute: typeof EventoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/territorio': {
      id: '/_authenticated/territorio'
      path: '/territorio'
      fullPath: '/territorio'
      preLoaderRoute: typeof AuthenticatedTerritorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/segmentos': {
      id: '/_authenticated/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof AuthenticatedSegmentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relacionamento': {
      id: '/_authenticated/relacionamento'
      path: '/relacionamento'
      fullPath: '/relacionamento'
      preLoaderRoute: typeof AuthenticatedRelacionamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-missoes': {
      id: '/_authenticated/minhas-missoes'
      path: '/minhas-missoes'
      fullPath: '/minhas-missoes'
      preLoaderRoute: typeof AuthenticatedMinhasMissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duplicidades': {
      id: '/_authenticated/duplicidades'
      path: '/duplicidades'
      fullPath: '/duplicidades'
      preLoaderRoute: typeof AuthenticatedDuplicidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos-bi': {
      id: '/_authenticated/contatos-bi'
      path: '/contatos-bi'
      fullPath: '/contatos-bi'
      preLoaderRoute: typeof AuthenticatedContatosBiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacao': {
      id: '/_authenticated/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof AuthenticatedComunicacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agitacao-notificacoes': {
      id: '/_authenticated/agitacao-notificacoes'
      path: '/agitacao-notificacoes'
      fullPath: '/agitacao-notificacoes'
      preLoaderRoute: typeof AuthenticatedAgitacaoNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agitacao': {
      id: '/_authenticated/agitacao'
      path: '/agitacao'
      fullPath: '/agitacao'
      preLoaderRoute: typeof AuthenticatedAgitacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes-agitacao/': {
      id: '/_authenticated/missoes-agitacao/'
      path: '/missoes-agitacao'
      fullPath: '/missoes-agitacao/'
      preLoaderRoute: typeof AuthenticatedMissoesAgitacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada-dados/': {
      id: '/_authenticated/entrada-dados/'
      path: '/entrada-dados'
      fullPath: '/entrada-dados/'
      preLoaderRoute: typeof AuthenticatedEntradaDadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos/': {
      id: '/_authenticated/contatos/'
      path: '/contatos'
      fullPath: '/contatos/'
      preLoaderRoute: typeof AuthenticatedContatosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacao/': {
      id: '/_authenticated/comunicacao/'
      path: '/'
      fullPath: '/comunicacao/'
      preLoaderRoute: typeof AuthenticatedComunicacaoIndexRouteImport
      parentRoute: typeof AuthenticatedComunicacaoRoute
    }
    '/_authenticated/campanhas/': {
      id: '/_authenticated/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof AuthenticatedCampanhasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios/papeis': {
      id: '/_authenticated/usuarios/papeis'
      path: '/papeis'
      fullPath: '/usuarios/papeis'
      preLoaderRoute: typeof AuthenticatedUsuariosPapeisRouteImport
      parentRoute: typeof AuthenticatedUsuariosRoute
    }
    '/_authenticated/triagem/$segmentId': {
      id: '/_authenticated/triagem/$segmentId'
      path: '/triagem/$segmentId'
      fullPath: '/triagem/$segmentId'
      preLoaderRoute: typeof AuthenticatedTriagemSegmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/triagem-tarefa/$token': {
      id: '/_authenticated/triagem-tarefa/$token'
      path: '/triagem-tarefa/$token'
      fullPath: '/triagem-tarefa/$token'
      preLoaderRoute: typeof AuthenticatedTriagemTarefaTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes-agitacao/$missionId': {
      id: '/_authenticated/missoes-agitacao/$missionId'
      path: '/missoes-agitacao/$missionId'
      fullPath: '/missoes-agitacao/$missionId'
      preLoaderRoute: typeof AuthenticatedMissoesAgitacaoMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada-dados/$id': {
      id: '/_authenticated/entrada-dados/$id'
      path: '/entrada-dados/$id'
      fullPath: '/entrada-dados/$id'
      preLoaderRoute: typeof AuthenticatedEntradaDadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos/$id': {
      id: '/_authenticated/contatos/$id'
      path: '/contatos/$id'
      fullPath: '/contatos/$id'
      preLoaderRoute: typeof AuthenticatedContatosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacao/inbox': {
      id: '/_authenticated/comunicacao/inbox'
      path: '/inbox'
      fullPath: '/comunicacao/inbox'
      preLoaderRoute: typeof AuthenticatedComunicacaoInboxRouteImport
      parentRoute: typeof AuthenticatedComunicacaoRoute
    }
    '/_authenticated/comunicacao/contatos': {
      id: '/_authenticated/comunicacao/contatos'
      path: '/contatos'
      fullPath: '/comunicacao/contatos'
      preLoaderRoute: typeof AuthenticatedComunicacaoContatosRouteImport
      parentRoute: typeof AuthenticatedComunicacaoRoute
    }
    '/_authenticated/campanhas/$id': {
      id: '/_authenticated/campanhas/$id'
      path: '/campanhas/$id'
      fullPath: '/campanhas/$id'
      preLoaderRoute: typeof AuthenticatedCampanhasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/missao/$missionId/contato/$contactId': {
      id: '/missao/$missionId/contato/$contactId'
      path: '/missao/$missionId/contato/$contactId'
      fullPath: '/missao/$missionId/contato/$contactId'
      preLoaderRoute: typeof MissaoMissionIdContatoContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zapi/$evento': {
      id: '/api/public/zapi/$evento'
      path: '/api/public/zapi/$evento'
      fullPath: '/api/public/zapi/$evento'
      preLoaderRoute: typeof ApiPublicZapiEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/vapid': {
      id: '/api/public/push/vapid'
      path: '/api/public/push/vapid'
      fullPath: '/api/public/push/vapid'
      preLoaderRoute: typeof ApiPublicPushVapidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/unsubscribe': {
      id: '/api/public/push/unsubscribe'
      path: '/api/public/push/unsubscribe'
      fullPath: '/api/public/push/unsubscribe'
      preLoaderRoute: typeof ApiPublicPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/subscribe': {
      id: '/api/public/push/subscribe'
      path: '/api/public/push/subscribe'
      fullPath: '/api/public/push/subscribe'
      preLoaderRoute: typeof ApiPublicPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/legal-pages/$slug': {
      id: '/api/public/legal-pages/$slug'
      path: '/api/public/legal-pages/$slug'
      fullPath: '/api/public/legal-pages/$slug'
      preLoaderRoute: typeof ApiPublicLegalPagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/process-campaign-queue': {
      id: '/api/public/jobs/process-campaign-queue'
      path: '/api/public/jobs/process-campaign-queue'
      fullPath: '/api/public/jobs/process-campaign-queue'
      preLoaderRoute: typeof ApiPublicJobsProcessCampaignQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/recadastro': {
      id: '/api/public/forms/recadastro'
      path: '/api/public/forms/recadastro'
      fullPath: '/api/public/forms/recadastro'
      preLoaderRoute: typeof ApiPublicFormsRecadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/opt-out': {
      id: '/api/public/forms/opt-out'
      path: '/api/public/forms/opt-out'
      fullPath: '/api/public/forms/opt-out'
      preLoaderRoute: typeof ApiPublicFormsOptOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/inscrever': {
      id: '/api/public/forms/inscrever'
      path: '/api/public/forms/inscrever'
      fullPath: '/api/public/forms/inscrever'
      preLoaderRoute: typeof ApiPublicFormsInscreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/cadastro-usuario': {
      id: '/api/public/forms/cadastro-usuario'
      path: '/api/public/forms/cadastro-usuario'
      fullPath: '/api/public/forms/cadastro-usuario'
      preLoaderRoute: typeof ApiPublicFormsCadastroUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/cadastro-agitador': {
      id: '/api/public/forms/cadastro-agitador'
      path: '/api/public/forms/cadastro-agitador'
      fullPath: '/api/public/forms/cadastro-agitador'
      preLoaderRoute: typeof ApiPublicFormsCadastroAgitadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug': {
      id: '/api/public/forms/$slug'
      path: '/api/public/forms/$slug'
      fullPath: '/api/public/forms/$slug'
      preLoaderRoute: typeof ApiPublicFormsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events/$slug': {
      id: '/api/public/events/$slug'
      path: '/api/public/events/$slug'
      fullPath: '/api/public/events/$slug'
      preLoaderRoute: typeof ApiPublicEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cep/$cep': {
      id: '/api/public/cep/$cep'
      path: '/api/public/cep/$cep'
      fullPath: '/api/public/cep/$cep'
      preLoaderRoute: typeof ApiPublicCepCepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug/section-progress': {
      id: '/api/public/forms/$slug/section-progress'
      path: '/section-progress'
      fullPath: '/api/public/forms/$slug/section-progress'
      preLoaderRoute: typeof ApiPublicFormsSlugSectionProgressRouteImport
      parentRoute: typeof ApiPublicFormsSlugRoute
    }
    '/api/public/forms/$slug/account-section': {
      id: '/api/public/forms/$slug/account-section'
      path: '/account-section'
      fullPath: '/api/public/forms/$slug/account-section'
      preLoaderRoute: typeof ApiPublicFormsSlugAccountSectionRouteImport
      parentRoute: typeof ApiPublicFormsSlugRoute
    }
    '/api/public/events/$slug/rsvp': {
      id: '/api/public/events/$slug/rsvp'
      path: '/rsvp'
      fullPath: '/api/public/events/$slug/rsvp'
      preLoaderRoute: typeof ApiPublicEventsSlugRsvpRouteImport
      parentRoute: typeof ApiPublicEventsSlugRoute
    }
    '/api/public/events/$slug/og-image': {
      id: '/api/public/events/$slug/og-image'
      path: '/og-image'
      fullPath: '/api/public/events/$slug/og-image'
      preLoaderRoute: typeof ApiPublicEventsSlugOgImageRouteImport
      parentRoute: typeof ApiPublicEventsSlugRoute
    }
    '/api/public/events/$slug/ics': {
      id: '/api/public/events/$slug/ics'
      path: '/ics'
      fullPath: '/api/public/events/$slug/ics'
      preLoaderRoute: typeof ApiPublicEventsSlugIcsRouteImport
      parentRoute: typeof ApiPublicEventsSlugRoute
    }
    '/api/public/events/$slug/cover': {
      id: '/api/public/events/$slug/cover'
      path: '/cover'
      fullPath: '/api/public/events/$slug/cover'
      preLoaderRoute: typeof ApiPublicEventsSlugCoverRouteImport
      parentRoute: typeof ApiPublicEventsSlugRoute
    }
    '/api/public/agitation-missions/$missionId/og-image': {
      id: '/api/public/agitation-missions/$missionId/og-image'
      path: '/api/public/agitation-missions/$missionId/og-image'
      fullPath: '/api/public/agitation-missions/$missionId/og-image'
      preLoaderRoute: typeof ApiPublicAgitationMissionsMissionIdOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agitation-missions/$missionId/media': {
      id: '/api/public/agitation-missions/$missionId/media'
      path: '/api/public/agitation-missions/$missionId/media'
      fullPath: '/api/public/agitation-missions/$missionId/media'
      preLoaderRoute: typeof ApiPublicAgitationMissionsMissionIdMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agitation-missions/$missionId/$contactId': {
      id: '/api/public/agitation-missions/$missionId/$contactId'
      path: '/api/public/agitation-missions/$missionId/$contactId'
      fullPath: '/api/public/agitation-missions/$missionId/$contactId'
      preLoaderRoute: typeof ApiPublicAgitationMissionsMissionIdContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedComunicacaoRouteChildren {
  AuthenticatedComunicacaoContatosRoute: typeof AuthenticatedComunicacaoContatosRoute
  AuthenticatedComunicacaoInboxRoute: typeof AuthenticatedComunicacaoInboxRoute
  AuthenticatedComunicacaoIndexRoute: typeof AuthenticatedComunicacaoIndexRoute
}

const AuthenticatedComunicacaoRouteChildren: AuthenticatedComunicacaoRouteChildren =
  {
    AuthenticatedComunicacaoContatosRoute:
      AuthenticatedComunicacaoContatosRoute,
    AuthenticatedComunicacaoInboxRoute: AuthenticatedComunicacaoInboxRoute,
    AuthenticatedComunicacaoIndexRoute: AuthenticatedComunicacaoIndexRoute,
  }

const AuthenticatedComunicacaoRouteWithChildren =
  AuthenticatedComunicacaoRoute._addFileChildren(
    AuthenticatedComunicacaoRouteChildren,
  )

interface AuthenticatedUsuariosRouteChildren {
  AuthenticatedUsuariosPapeisRoute: typeof AuthenticatedUsuariosPapeisRoute
}

const AuthenticatedUsuariosRouteChildren: AuthenticatedUsuariosRouteChildren = {
  AuthenticatedUsuariosPapeisRoute: AuthenticatedUsuariosPapeisRoute,
}

const AuthenticatedUsuariosRouteWithChildren =
  AuthenticatedUsuariosRoute._addFileChildren(
    AuthenticatedUsuariosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgitacaoRoute: typeof AuthenticatedAgitacaoRoute
  AuthenticatedAgitacaoNotificacoesRoute: typeof AuthenticatedAgitacaoNotificacoesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedComunicacaoRoute: typeof AuthenticatedComunicacaoRouteWithChildren
  AuthenticatedContatosBiRoute: typeof AuthenticatedContatosBiRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDuplicidadesRoute: typeof AuthenticatedDuplicidadesRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedMinhasMissoesRoute: typeof AuthenticatedMinhasMissoesRoute
  AuthenticatedRelacionamentoRoute: typeof AuthenticatedRelacionamentoRoute
  AuthenticatedSegmentosRoute: typeof AuthenticatedSegmentosRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedTerritorioRoute: typeof AuthenticatedTerritorioRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRouteWithChildren
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedCampanhasIdRoute: typeof AuthenticatedCampanhasIdRoute
  AuthenticatedContatosIdRoute: typeof AuthenticatedContatosIdRoute
  AuthenticatedEntradaDadosIdRoute: typeof AuthenticatedEntradaDadosIdRoute
  AuthenticatedMissoesAgitacaoMissionIdRoute: typeof AuthenticatedMissoesAgitacaoMissionIdRoute
  AuthenticatedTriagemTarefaTokenRoute: typeof AuthenticatedTriagemTarefaTokenRoute
  AuthenticatedTriagemSegmentIdRoute: typeof AuthenticatedTriagemSegmentIdRoute
  AuthenticatedCampanhasIndexRoute: typeof AuthenticatedCampanhasIndexRoute
  AuthenticatedContatosIndexRoute: typeof AuthenticatedContatosIndexRoute
  AuthenticatedEntradaDadosIndexRoute: typeof AuthenticatedEntradaDadosIndexRoute
  AuthenticatedMissoesAgitacaoIndexRoute: typeof AuthenticatedMissoesAgitacaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgitacaoRoute: AuthenticatedAgitacaoRoute,
  AuthenticatedAgitacaoNotificacoesRoute:
    AuthenticatedAgitacaoNotificacoesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedComunicacaoRoute: AuthenticatedComunicacaoRouteWithChildren,
  AuthenticatedContatosBiRoute: AuthenticatedContatosBiRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDuplicidadesRoute: AuthenticatedDuplicidadesRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedMinhasMissoesRoute: AuthenticatedMinhasMissoesRoute,
  AuthenticatedRelacionamentoRoute: AuthenticatedRelacionamentoRoute,
  AuthenticatedSegmentosRoute: AuthenticatedSegmentosRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedTerritorioRoute: AuthenticatedTerritorioRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRouteWithChildren,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedCampanhasIdRoute: AuthenticatedCampanhasIdRoute,
  AuthenticatedContatosIdRoute: AuthenticatedContatosIdRoute,
  AuthenticatedEntradaDadosIdRoute: AuthenticatedEntradaDadosIdRoute,
  AuthenticatedMissoesAgitacaoMissionIdRoute:
    AuthenticatedMissoesAgitacaoMissionIdRoute,
  AuthenticatedTriagemTarefaTokenRoute: AuthenticatedTriagemTarefaTokenRoute,
  AuthenticatedTriagemSegmentIdRoute: AuthenticatedTriagemSegmentIdRoute,
  AuthenticatedCampanhasIndexRoute: AuthenticatedCampanhasIndexRoute,
  AuthenticatedContatosIndexRoute: AuthenticatedContatosIndexRoute,
  AuthenticatedEntradaDadosIndexRoute: AuthenticatedEntradaDadosIndexRoute,
  AuthenticatedMissoesAgitacaoIndexRoute:
    AuthenticatedMissoesAgitacaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicEventsSlugRouteChildren {
  ApiPublicEventsSlugCoverRoute: typeof ApiPublicEventsSlugCoverRoute
  ApiPublicEventsSlugIcsRoute: typeof ApiPublicEventsSlugIcsRoute
  ApiPublicEventsSlugOgImageRoute: typeof ApiPublicEventsSlugOgImageRoute
  ApiPublicEventsSlugRsvpRoute: typeof ApiPublicEventsSlugRsvpRoute
}

const ApiPublicEventsSlugRouteChildren: ApiPublicEventsSlugRouteChildren = {
  ApiPublicEventsSlugCoverRoute: ApiPublicEventsSlugCoverRoute,
  ApiPublicEventsSlugIcsRoute: ApiPublicEventsSlugIcsRoute,
  ApiPublicEventsSlugOgImageRoute: ApiPublicEventsSlugOgImageRoute,
  ApiPublicEventsSlugRsvpRoute: ApiPublicEventsSlugRsvpRoute,
}

const ApiPublicEventsSlugRouteWithChildren =
  ApiPublicEventsSlugRoute._addFileChildren(ApiPublicEventsSlugRouteChildren)

interface ApiPublicFormsSlugRouteChildren {
  ApiPublicFormsSlugAccountSectionRoute: typeof ApiPublicFormsSlugAccountSectionRoute
  ApiPublicFormsSlugSectionProgressRoute: typeof ApiPublicFormsSlugSectionProgressRoute
}

const ApiPublicFormsSlugRouteChildren: ApiPublicFormsSlugRouteChildren = {
  ApiPublicFormsSlugAccountSectionRoute: ApiPublicFormsSlugAccountSectionRoute,
  ApiPublicFormsSlugSectionProgressRoute:
    ApiPublicFormsSlugSectionProgressRoute,
}

const ApiPublicFormsSlugRouteWithChildren =
  ApiPublicFormsSlugRoute._addFileChildren(ApiPublicFormsSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  AtualizacaoRoute: AtualizacaoRoute,
  AuthRoute: AuthRoute,
  CadastroAgitadorRoute: CadastroAgitadorRoute,
  CadastroUsuarioRoute: CadastroUsuarioRoute,
  InscreverRoute: InscreverRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  RecadastroRoute: RecadastroRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  EventoSlugRoute: EventoSlugRoute,
  FSlugRoute: FSlugRoute,
  OptOutTokenRoute: OptOutTokenRoute,
  TermosSlugRoute: TermosSlugRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicCepCepRoute: ApiPublicCepCepRoute,
  ApiPublicEventsSlugRoute: ApiPublicEventsSlugRouteWithChildren,
  ApiPublicFormsSlugRoute: ApiPublicFormsSlugRouteWithChildren,
  ApiPublicFormsCadastroAgitadorRoute: ApiPublicFormsCadastroAgitadorRoute,
  ApiPublicFormsCadastroUsuarioRoute: ApiPublicFormsCadastroUsuarioRoute,
  ApiPublicFormsInscreverRoute: ApiPublicFormsInscreverRoute,
  ApiPublicFormsOptOutRoute: ApiPublicFormsOptOutRoute,
  ApiPublicFormsRecadastroRoute: ApiPublicFormsRecadastroRoute,
  ApiPublicJobsProcessCampaignQueueRoute:
    ApiPublicJobsProcessCampaignQueueRoute,
  ApiPublicLegalPagesSlugRoute: ApiPublicLegalPagesSlugRoute,
  ApiPublicPushSubscribeRoute: ApiPublicPushSubscribeRoute,
  ApiPublicPushUnsubscribeRoute: ApiPublicPushUnsubscribeRoute,
  ApiPublicPushVapidRoute: ApiPublicPushVapidRoute,
  ApiPublicZapiEventoRoute: ApiPublicZapiEventoRoute,
  MissaoMissionIdContatoContactIdRoute: MissaoMissionIdContatoContactIdRoute,
  ApiPublicAgitationMissionsMissionIdContactIdRoute:
    ApiPublicAgitationMissionsMissionIdContactIdRoute,
  ApiPublicAgitationMissionsMissionIdMediaRoute:
    ApiPublicAgitationMissionsMissionIdMediaRoute,
  ApiPublicAgitationMissionsMissionIdOgImageRoute:
    ApiPublicAgitationMissionsMissionIdOgImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
